### PR TITLE
Fix #161: ServiceRestClient fails when forExternalService() used together with onUrlFromTemplate()

### LINKED ISSUE #161: ServiceRestClient fails when forExternalService() used together with onUrlFromTemplate()
This URL used in `ServiceRestClient` is fine: `http://localhost:8080/$id"`. However this: `$host/$id`  will fail due to some bizarre reason. Bug introduced in #148, the simplest workaround is to either use `urlFromTemplate()` explicitly or cast `GString` to `String`.

See also: 4finance/boot-microservice#26

### PR DESCRIPTION
**Pull request by nurkiewicz**

### CODE REVIEW

File: micro-infra-spring-base/src/test/resources/logback.groovy [hunk 1]
```diff
@@ -10,5 +10,5 @@ appender("CONSOLE", ConsoleAppender) {
 //TODO: Fix console pollution during tests (it should be only logged to a test log file, but also available in Gradle test reports)
```
Comment (szpak) [inline micro-infra-spring-base/src/test/resources/logback.groovy]: Why have you renamed logback-test.groovy to logback.groovy?

File: micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/common/response/receive/MethodParamsApplier.groovy [hunk 2]
```diff
@@ -43,9 +43,24 @@ trait MethodParamsApplier<M, EM, PM> implements HttpMethod<M, PM>, HttpEntitySen
...
+            replaceFirstPlaceholderWithValue()
+        }
         this
     }
 
+    private void replaceFirstPlaceholderWithValue() {
+        final String template = params.urlTemplate
+        final String skippedFirstPlaceholder = StringUtils.substringAfter(template, '}')
+        final Object[] variables = params.urlVariablesArray
+        params.urlTemplate = variables[0] + skippedFirstPlaceholder
```
Comment (szpak) [inline micro-infra-spring-base/src/main/groovy/com/ofg/infrastructure/web/resttemplate/fluent/common/response/receive/MethodParamsApplier.groovy]: Maybe `variables.head()`?
